name: Publish changes

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Publish to pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: src
          target-branch: pages
